# Generated by Django 2.0.6 on 2018-06-17 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('document', models.FileField(blank=True, upload_to='downloads/%Y/%m/%d')),
                ('version_free', models.FileField(blank=True, upload_to='downloads/%Y/%m/%d')),
                ('version_premium', models.FileField(blank=True, upload_to='downloads/%Y/%m/%d')),
                ('free', models.BooleanField(default=False)),
                ('support', models.BooleanField(default=False)),
                ('documentation', models.BooleanField(default=False)),
                ('framework_css', models.CharField(choices=[('Bootstrap_4', 'Bootstrap_4'), ('Bluma', 'Bluma')], default='bluma', max_length=14)),
                ('framework_js', models.CharField(choices=[('Vue', 'Vue'), ('Angular', 'Angular'), ('React', 'React')], default='bluma', max_length=14)),
                ('components', models.DecimalField(decimal_places=0, default=False, max_digits=10)),
                ('examples_pages', models.DecimalField(decimal_places=0, default=False, max_digits=10)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
