# Generated by Django 2.0.6 on 2018-06-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180617_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
